# Generated by Django 4.2.23 on 2025-10-01 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
